name: 'Slack Notify'
description: 'MacOS runner compatible Slack notification'
inputs:
  username:  # id of input
    description: 'Username as it will appear in Slack'
    required: true
    default: 'MyApp'
  icon:
    description: 'Icon to use'
    required: true
    default: ghost
  channel:
    description: 'Slack channel name without #'
    required: true
    default: general
  webhook_url:
    description: "Slack channel webhook URL"
    required: true
  message:
    description: "message body"
    required: true
    default: "lorem ipsum hatchum batchum"
runs:
  using: "composite"
  steps: 
    - run: ${{ github.action_path }}/slack_message.sh ${{ inputs.webhook_url }} ${{ inputs.channel }} ${{ inputs.username }} ${{ inputs.icon }} ${{ inputs.message }}
      shell: bash

